//.....Create a function that filter out negative numbers...............
function filterNegative() {


    let ar = document.getElementById('arfield').value;
    // console.log(typeof ar)
    var splited = ar.split(",")
    let filter = []//store the new value.........
    //....loop will be  start from 0 and index is less than array of length......... 
    for (var index = 0; index < splited.length; index++) {
        //.....if check the condition array of index is less then 0......
        if (splited[index] < 0) {
            //...Add the negative value in the new array.........
            filter.push(splited[index])
        }
    }

    document.getElementById('result').innerHTML=filter;

}
// let ar = [-40, -60, 80, 50, 20, 30];
// let Filter = []//store the new value.........
// //....loop will be  start from 0 and index is less than array of length......... 
// for (var index = 0; index < ar.length; index++) {
//     //.....if check the condition array of index is less then 0......
//     if (ar[index] < 0) {
//         //...Add the negative value in the new array.........
//         Filter.push(ar[index])
//     }
// }

// console.log(Filter);//find the final result..........